services:
  - type: web
    name: knifehub
    env: docker
    plan: free
    repo: https://github.com/yiyungent/KnifeHub.git
    dockerfilePath: ./deploy/render/Dockerfile
    dockerContext: ./deploy/render/
    healthCheckPath: /PluginCore/Admin # hanging
    envVars:
      - key: PLUGINCORE_ADMIN_USERNAME
        value: admin
      - key: PLUGINCORE_ADMIN_PASSWORD
        value: ABC12345
    autoDeploy: true
