name: plugins MemosPlus NuGet Push

on:
  push:
    tags:
      - "MemosPlus-v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.100

      - name: Build and Pack
        run: |
          cd ./plugins/MemosPlus
          dotnet pack --configuration Release
          dotnet pack --configuration Release -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
          ls
          ls ./bin/Release/
        shell: bash

      - name: Add private GitHub registry to NuGet
        run: |
          dotnet nuget add source https://nuget.pkg.github.com/yiyungent/index.json --name github --username yiyungent --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
        shell: bash

      - name: Push generated package to GitHub registry and NuGet
        run: |
          dotnet nuget push ./plugins/MemosPlus/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate --api-key ${{ secrets.PLUGINCORE_NUGET_KEY }}
          dotnet nuget push ./plugins/MemosPlus/bin/Release/*.nupkg --source github --skip-duplicate --api-key ${{ secrets.GITHUB_TOKEN }}
        shell: bash
